name: OchronaSpawna
version: 1.0
main: pl.ochronaspawna.OchronaSpawna
api-version: '1.21'

commands:
  sw:
    description: Komendy OchronaSpawna
    usage: /sw <wand|create|delete|list>
    permission: ochronaspawna.admin

permissions:
  ochronaspawna.admin:
    default: op
