name: Build SpawnW0dka

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Ustaw Jave 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Zbuduj plugin
        run: mvn clean package

      - name: Zapisz plugin
        uses: actions/upload-artifact@v4
        with:
          name: SpawnW0dka
          path: target/*.jar
